[package]
name = "smt"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/smt"
description = "A template for creating Rust open-source repo on GitHub"
license = "MIT/Apache-2.0"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = []
std = ["kvstructs/default", "bytes/default"]

[dependencies]
bytes = { version = "1.2", default-features = false }
digest = "0.10"
kvstructs = { version = "0.0.23", default-features = false }
sha2 = { version = "0.10", default-features = false, optional = true }

[dev-dependencies]
criterion = "0.3"
tempfile = "3"
parking_lot = "0.12"
sha2 = "0.10"
hashbrown = "0.12"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
